site_name: Team Documentation
site_description: Documentation for the team
site_author: Mikkel

theme:
  name: dracula

nav:
  - Home: index.md
  - About: about.md
  - Guidelines: guidelines.md
  - Git-stragegy: git-strategy.md
  - Static-code-analysis: static-code-analysis.md
  - Unit-testing: unit-testing.md
  - E2e-testing: e2e-testing.md
  - Refactoring: refactoring.md
  - GitHub-actions: github-actions.md